import SidebarWithHeader from "components/Sidebar";
import Head from "next/head";
import { PropsWithChildren } from "react";

export const DefaultContainer = (props: PropsWithChildren<{}>) => {
  const { children } = props;
  return (
    <>
      <Head>
        <title>Solart Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <SidebarWithHeader>
        <main>{children}</main>
      </SidebarWithHeader>
    </>
  );
};
