import { Text } from "@chakra-ui/react";
import { useCreateImage } from "hooks/useCreateImage";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

export default function Home() {
  const createImage = useCreateImage();

  useEffect(() => {
    (async function () {
      await createImage.mutateAsync();
    })();
  }, []);

  useEffect(() => {
    console.log(createImage.data);
  }, [createImage.data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {createImage.isLoading && "Loading"}
        {createImage.isSuccess && (
          <>
            <img src={createImage.data.imageUri} width={1024} height={1024} />
            <Text>{createImage.data.prompt}</Text>
          </>
        )}
      </main>
    </>
  );
}
